### PR TITLE
Added support for Windows

### PR DESCRIPTION
**Pull request by creotiv**

### CODE REVIEW

**Comment by jalada** [comment]
Thanks @creotiv! We're fully stacked at Pixie Labs at the moment, but when we're a bit quieter we'll get this tested, merged and released. Thanks for your help!

**Comment by jalada** [comment]
Hi @creotiv! I think we'd actually like to solve this by using Node's proper File APIs to rename/move the files, rather than continuing to add platform-specific command line definitions. Running stuff as commands is a bit of a hack. Using the proper APIs allows us to defer the platform testing to Node by abstracting away from the implementation, instead of having to test on all platforms ourselves.

This is on our roadmap to fix, and we've got some time allocated to Cavy over the coming weeks, but feel free to beat me to it if you have time 👍🏻 

Thanks again!

**Comment by creotiv** [comment]
I think you can add this now, and then replace on Node api. Cause right now
cli on windows is failing.

Kindly yours,
Andrey Nikishaev

Areas         ML/DS/CV/Soft Dev/BizDev/Growth Hacking/Customer Rel/IT
LinkedIn      http://ua.linkedin.com/in/creotiv
GitHub        http://github.com/creotiv
Slideshare  https://www.slideshare.net/anikishaev/
Skype         creotiv.in.ua
Mobile        +380632410666

**Comment by AbigailMcP** [comment]
Closing as this is fixed by https://github.com/pixielabs/cavy-cli/pull/39 - will be included in release today!

**Pull request closed without merging**
